/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_pack;

import java.util.ArrayList;
import projecteuf56.DetallsJugador;
import projecteuf56.Jugadors;
import projecteuf56.PrimeraTaula;
import static projecteuf56.PrimeraTaula.numJug;
import projecteuf56.SegonaTaula;

/**
 *
 * @author sonnymccammond
 */
public class MorePlayerFrame extends javax.swing.JFrame {

    /**
     * Creates new form MorePlayerFrame
     */
    public MorePlayerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerPosition = new javax.swing.JLabel();
        playerGoals = new javax.swing.JLabel();
        playerAssists = new javax.swing.JLabel();
        positionInput = new javax.swing.JLabel();
        goalInput = new javax.swing.JLabel();
        assistsInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerPosition.setText("Posició Jugada:");

        playerGoals.setText("Gols Marcats:");

        playerAssists.setText("Assistencies:");

        positionInput.setText("Posició");

        goalInput.setText("Gols");

        assistsInput.setText("Assistencies");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerPosition)
                    .addComponent(playerGoals)
                    .addComponent(playerAssists))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assistsInput)
                    .addComponent(goalInput)
                    .addComponent(positionInput))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerPosition)
                    .addComponent(positionInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerGoals)
                    .addComponent(goalInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerAssists)
                    .addComponent(assistsInput))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarDetalls() {
        PlayerFrame pf = new PlayerFrame();
        ArrayList<DetallsJugador> dj = SegonaTaula.llistarDetalls(numJug.get(pf.indexPresentat).getNom());
        String pos = dj.get(pf.indexPresentat).getPosicio();
        int gol = dj.get(pf.indexPresentat).getGols();
        int ass = dj.get(pf.indexPresentat).getAsistencies();
        
        positionInput.setText(pos);
        goalInput.setText(gol + "");
        assistsInput.setText(ass + "");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MorePlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MorePlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MorePlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MorePlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MorePlayerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assistsInput;
    private javax.swing.JLabel goalInput;
    private javax.swing.JLabel playerAssists;
    private javax.swing.JLabel playerGoals;
    private javax.swing.JLabel playerPosition;
    private javax.swing.JLabel positionInput;
    // End of variables declaration//GEN-END:variables
}
