/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_pack;

import java.util.ArrayList;
import projecteuf56.DetallsJugador;
import projecteuf56.Jugadors;
import projecteuf56.PrimeraTaula;
import static projecteuf56.PrimeraTaula.numJug;
import projecteuf56.SegonaTaula;

//Cicla llista registres
/**
 *
 * @author sonnymccammond
 */
public class MorePlayerFrame extends javax.swing.JFrame {

    int indexNom = PlayerFrame.indexPresentat;
    int indexDetalls = 0;
    ArrayList<DetallsJugador> dj = SegonaTaula.llistarDetalls(numJug.get(indexNom).getNom());

    /**
     * Creates new form MorePlayerFrame
     */
    public MorePlayerFrame() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerPosition = new javax.swing.JLabel();
        playerGoals = new javax.swing.JLabel();
        playerAssists = new javax.swing.JLabel();
        positionInput = new javax.swing.JLabel();
        goalInput = new javax.swing.JLabel();
        assistsInput = new javax.swing.JLabel();
        after = new javax.swing.JButton();
        before = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playerPosition.setText("Posició Jugada:");

        playerGoals.setText("Gols Marcats:");

        playerAssists.setText("Assistencies:");

        positionInput.setText("Posició");

        goalInput.setText("Gols");

        assistsInput.setText("Assistencies");

        after.setText("Més Detalls >");
        after.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afterActionPerformed(evt);
            }
        });

        before.setText("< Detalls Previs");
        before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beforeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(before)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(after)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerPosition)
                    .addComponent(playerGoals)
                    .addComponent(playerAssists))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assistsInput)
                    .addComponent(goalInput)
                    .addComponent(positionInput))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(after)
                    .addComponent(before))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerPosition)
                    .addComponent(positionInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerGoals)
                    .addComponent(goalInput))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerAssists)
                    .addComponent(assistsInput))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beforeActionPerformed
        if (indexDetalls == 0) {
            indexDetalls = dj.size() - 1;
        } else {
            indexDetalls--;
        }
        mostrarDetalls();
    }//GEN-LAST:event_beforeActionPerformed

    private void afterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afterActionPerformed
        if (indexDetalls == dj.size()) {
            indexDetalls = 0;
        } else {
            indexDetalls++;
        }
        mostrarDetalls();
    }//GEN-LAST:event_afterActionPerformed

    public void mostrarDetalls() {

        String pos = dj.get(indexDetalls).getPosicio();
        int gol = dj.get(indexDetalls).getGols();
        int ass = dj.get(indexDetalls).getAssistencies();

        positionInput.setText(pos);
        goalInput.setText(gol + "");
        assistsInput.setText(ass + "");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MorePlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MorePlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MorePlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MorePlayerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MorePlayerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton after;
    private javax.swing.JLabel assistsInput;
    private javax.swing.JButton before;
    private javax.swing.JLabel goalInput;
    private javax.swing.JLabel playerAssists;
    private javax.swing.JLabel playerGoals;
    private javax.swing.JLabel playerPosition;
    private javax.swing.JLabel positionInput;
    // End of variables declaration//GEN-END:variables
}
